// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package mkdb

import (
	"context"
)

// iteratorForCreateTags implements pgx.CopyFromSource.
type iteratorForCreateTags struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTags) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTags) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateTags) Err() error {
	return nil
}

func (q *Queries) CreateTags(ctx context.Context, value []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tags"}, []string{"value"}, &iteratorForCreateTags{rows: value})
}
