// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package mkdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string
	AccountId             string
	ProviderId            string
	UserId                string
	AccessToken           pgtype.Text
	RefreshToken          pgtype.Text
	IdToken               pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	Scope                 pgtype.Text
	Password              pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Jwk struct {
	ID         string
	PublicKey  string
	PrivateKey string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type Post struct {
	ID            int32
	Title         string
	Description   string
	Accountposted string
	Createdate    pgtype.Timestamptz
	Updatedate    pgtype.Timestamptz
	Resource      int32
	Url           pgtype.Text
	Content       pgtype.Text
}

type PostsTag struct {
	PostID int32
	TagID  int32
}

type ResourceType struct {
	ID    int32
	Value string
}

type Session struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Token     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	UserId    string
}

type Tag struct {
	ID    int32
	Value string
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
